name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bats
      run: |
        sudo apt-get update
        sudo apt-get install -y bats

    - name: Run Bats tests
      run: |
        cd test
        bats test_check_and_create_dir.bats
